Added support for publishing wheel files.

diff --git a/scripts/publish b/scripts/publish
--- a/scripts/publish
+++ b/scripts/publish
@@ -12,10 +12,16 @@ if ! command -v "${PREFIX}twine" &>/dev/null ; then
     exit 1
 fi
 
+if ! command -v "${PREFIX}wheel" &>/dev/null ; then
+    echo "Unable to find the 'wheel' command."
+    echo "Install from PyPI, using '${PREFIX}pip install wheel'."
+    exit 1
+fi
+
 find uvicorn -type f -name "*.py[co]" -delete
 find uvicorn -type d -name __pycache__ -delete
 
-${PREFIX}python setup.py sdist
+${PREFIX}python setup.py sdist bdist_wheel
 ${PREFIX}twine upload dist/*
 
 echo "You probably want to also tag the version now:"
